### ISSUE TITLE
Bind python folder to /app in Docker-Compose

### ISSUE THREAD

**Issue by finish06** [pharmorg/OpenFDA#5]

**Comment by yevgenybulochnik** [comment]
Currently whenever there is a file change in the source code the server does not reload automatically in docker. This is because the source code is not mounted inside the docker container. To update the container we currently need to run `docker-compose up --build` on every file change. For reference [docker volumes](https://docs.docker.com/compose/compose-file/#volumes)

**Comment by hl1** [comment]
assigning this to myself but if you get the time to do it, it is all yours. I need an intro docker before I can do this request.

**Comment by yevgenybulochnik** [comment]
Newest PR addresses application volume bind
